In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df=pd.read_csv("/content/drive/MyDrive/Machin Learning/diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [5]:
x=df.drop("Outcome",axis=1)
x
y=df["Outcome"]
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [6]:

x=np.array(x)
x
y=np.array(y)
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [9]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((614, 8), (154, 8), (614,), (154,))

In [30]:
from sklearn.tree import DecisionTreeClassifier

dt=DecisionTreeClassifier(max_depth=18,min_samples_split=2,min_samples_leaf=1)
dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=18)

In [38]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(n_estimators=200,max_depth=18,min_samples_split=2,min_samples_leaf=1)
rf.fit(x_train,y_train)

RandomForestClassifier(max_depth=18, n_estimators=200)

In [39]:
#DecisionTree
dt_test_predict=dt.predict(x_test)
dt_train_predict=dt.predict(x_train)
#Random Forest
rf_test_predict=rf.predict(x_test)
rf_train_predict=rf.predict(x_train)

In [24]:
from sklearn.metrics import precision_score,recall_score,accuracy_score,confusion_matrix

In [40]:
ps_dt=precision_score(y_test,dt_test_predict)
ps_rf=precision_score(y_test,rf_test_predict)
ps_dt,ps_rf

(0.6122448979591837, 0.7111111111111111)

In [41]:
ps_dt=precision_score(y_train,dt_train_predict)
ps_rf=precision_score(y_train,rf_train_predict)
ps_dt,ps_rf

(1.0, 1.0)

In [42]:
dt_test_acc=accuracy_score(y_test,dt_test_predict)
dt_train_acc=accuracy_score(y_train,dt_train_predict)

rf_test_acc=accuracy_score(y_test,rf_test_predict)
rf_train_acc=accuracy_score(y_train,rf_train_predict)

dt_test_acc,dt_train_acc,rf_test_acc,rf_train_acc


(0.7857142857142857, 1.0, 0.8376623376623377, 1.0)

In [43]:
dt_rc_test=recall_score(y_test,dt_test_predict)
dt_rc_train=recall_score(y_train,dt_train_predict)

rf_rc_test=recall_score(y_test,rf_test_predict)
rf_rc_train=recall_score(y_train,rf_train_predict)

dt_rc_test,dt_rc_train,rf_rc_test,rf_rc_train

(0.6818181818181818, 1.0, 0.7272727272727273, 1.0)

In [44]:
dt_cm_test=confusion_matrix(y_test,dt_test_predict)
dt_cm_train=confusion_matrix(y_train,dt_train_predict)

rf_cm_test=confusion_matrix(y_test,rf_test_predict)
rf_cm_train=confusion_matrix(y_train,rf_train_predict)

dt_cm_test,dt_cm_train,rf_cm_test,rf_cm_train


(array([[91, 19],
        [14, 30]]),
 array([[390,   0],
        [  0, 224]]),
 array([[97, 13],
        [12, 32]]),
 array([[390,   0],
        [  0, 224]]))